#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouHoo.DataBll
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Epumping_2017")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertDepartment(Department instance);
    partial void UpdateDepartment(Department instance);
    partial void DeleteDepartment(Department instance);
    partial void InsertPerson(Person instance);
    partial void UpdatePerson(Person instance);
    partial void DeletePerson(Person instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::YouHoo.DataBll.Properties.Settings.Default.Epumping_2017ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Department> Department
		{
			get
			{
				return this.GetTable<Department>();
			}
		}
		
		public System.Data.Linq.Table<Person> Person
		{
			get
			{
				return this.GetTable<Person>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Department")]
	public partial class Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cDepCode;
		
		private string _cDepName;
		
		private string _cDepFullName;
		
		private System.Nullable<byte> _iDepGrade;
		
		private System.Nullable<bool> _bDepEnd;
		
		private string _cDepPerson;
		
		private string _cDepMemo;
		
		private System.Data.Linq.Binary _pubufts;
		
		private System.Nullable<System.DateTime> _dDepBeginDate;
		
		private System.Nullable<System.DateTime> _dDepEndDate;
		
		private System.Nullable<decimal> _CompanyID;
		
		private string _cAsynTs;
		
		private EntitySet<Person> _Person;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncDepCodeChanging(string value);
    partial void OncDepCodeChanged();
    partial void OncDepNameChanging(string value);
    partial void OncDepNameChanged();
    partial void OncDepFullNameChanging(string value);
    partial void OncDepFullNameChanged();
    partial void OniDepGradeChanging(System.Nullable<byte> value);
    partial void OniDepGradeChanged();
    partial void OnbDepEndChanging(System.Nullable<bool> value);
    partial void OnbDepEndChanged();
    partial void OncDepPersonChanging(string value);
    partial void OncDepPersonChanged();
    partial void OncDepMemoChanging(string value);
    partial void OncDepMemoChanged();
    partial void OnpubuftsChanging(System.Data.Linq.Binary value);
    partial void OnpubuftsChanged();
    partial void OndDepBeginDateChanging(System.Nullable<System.DateTime> value);
    partial void OndDepBeginDateChanged();
    partial void OndDepEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OndDepEndDateChanged();
    partial void OnCompanyIDChanging(System.Nullable<decimal> value);
    partial void OnCompanyIDChanged();
    partial void OncAsynTsChanging(string value);
    partial void OncAsynTsChanged();
    #endregion
		
		public Department()
		{
			this._Person = new EntitySet<Person>(new Action<Person>(this.attach_Person), new Action<Person>(this.detach_Person));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDepCode", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string cDepCode
		{
			get
			{
				return this._cDepCode;
			}
			set
			{
				if ((this._cDepCode != value))
				{
					this.OncDepCodeChanging(value);
					this.SendPropertyChanging();
					this._cDepCode = value;
					this.SendPropertyChanged("cDepCode");
					this.OncDepCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDepName", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string cDepName
		{
			get
			{
				return this._cDepName;
			}
			set
			{
				if ((this._cDepName != value))
				{
					this.OncDepNameChanging(value);
					this.SendPropertyChanging();
					this._cDepName = value;
					this.SendPropertyChanged("cDepName");
					this.OncDepNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDepFullName", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string cDepFullName
		{
			get
			{
				return this._cDepFullName;
			}
			set
			{
				if ((this._cDepFullName != value))
				{
					this.OncDepFullNameChanging(value);
					this.SendPropertyChanging();
					this._cDepFullName = value;
					this.SendPropertyChanged("cDepFullName");
					this.OncDepFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iDepGrade", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> iDepGrade
		{
			get
			{
				return this._iDepGrade;
			}
			set
			{
				if ((this._iDepGrade != value))
				{
					this.OniDepGradeChanging(value);
					this.SendPropertyChanging();
					this._iDepGrade = value;
					this.SendPropertyChanged("iDepGrade");
					this.OniDepGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bDepEnd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> bDepEnd
		{
			get
			{
				return this._bDepEnd;
			}
			set
			{
				if ((this._bDepEnd != value))
				{
					this.OnbDepEndChanging(value);
					this.SendPropertyChanging();
					this._bDepEnd = value;
					this.SendPropertyChanged("bDepEnd");
					this.OnbDepEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDepPerson", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cDepPerson
		{
			get
			{
				return this._cDepPerson;
			}
			set
			{
				if ((this._cDepPerson != value))
				{
					this.OncDepPersonChanging(value);
					this.SendPropertyChanging();
					this._cDepPerson = value;
					this.SendPropertyChanged("cDepPerson");
					this.OncDepPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDepMemo", DbType="NVarChar(400)", UpdateCheck=UpdateCheck.Never)]
		public string cDepMemo
		{
			get
			{
				return this._cDepMemo;
			}
			set
			{
				if ((this._cDepMemo != value))
				{
					this.OncDepMemoChanging(value);
					this.SendPropertyChanging();
					this._cDepMemo = value;
					this.SendPropertyChanged("cDepMemo");
					this.OncDepMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubufts", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary pubufts
		{
			get
			{
				return this._pubufts;
			}
			set
			{
				if ((this._pubufts != value))
				{
					this.OnpubuftsChanging(value);
					this.SendPropertyChanging();
					this._pubufts = value;
					this.SendPropertyChanged("pubufts");
					this.OnpubuftsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dDepBeginDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dDepBeginDate
		{
			get
			{
				return this._dDepBeginDate;
			}
			set
			{
				if ((this._dDepBeginDate != value))
				{
					this.OndDepBeginDateChanging(value);
					this.SendPropertyChanging();
					this._dDepBeginDate = value;
					this.SendPropertyChanged("dDepBeginDate");
					this.OndDepBeginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dDepEndDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dDepEndDate
		{
			get
			{
				return this._dDepEndDate;
			}
			set
			{
				if ((this._dDepEndDate != value))
				{
					this.OndDepEndDateChanging(value);
					this.SendPropertyChanging();
					this._dDepEndDate = value;
					this.SendPropertyChanged("dDepEndDate");
					this.OndDepEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Decimal(18,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cAsynTs", DbType="VarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string cAsynTs
		{
			get
			{
				return this._cAsynTs;
			}
			set
			{
				if ((this._cAsynTs != value))
				{
					this.OncAsynTsChanging(value);
					this.SendPropertyChanging();
					this._cAsynTs = value;
					this.SendPropertyChanged("cAsynTs");
					this.OncAsynTsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Department_Person", Storage="_Person", ThisKey="cDepCode", OtherKey="cDepCode")]
		public EntitySet<Person> Person
		{
			get
			{
				return this._Person;
			}
			set
			{
				this._Person.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Person(Person entity)
		{
			this.SendPropertyChanging();
			entity.Department = this;
		}
		
		private void detach_Person(Person entity)
		{
			this.SendPropertyChanging();
			entity.Department = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Person")]
	public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _PersonId;
		
		private string _cDepCode;
		
		private string _cPsn_Num;
		
		private string _cPsn_Name;
		
		private System.Nullable<System.DateTime> _dLeaveDate;
		
		private string _cLeaveReson;
		
		private string _cJobCode;
		
		private string _JobNumber;
		
		private string _cPersonBarCode;
		
		private string _rPersonType;
		
		private string _cPsnMobilePhone;
		
		private string _cPsnEmail;
		
		private string _cPsnQQCode;
		
		private System.Nullable<char> _nameCharFirst;
		
		private System.Nullable<bool> _bHaveAccount;
		
		private string _loginName;
		
		private string _cHeadUrl;
		
		private string _cAsynTs;
		
		private string _AreaCode;
		
		private System.Nullable<bool> _bPersonAppUser;
		
		private System.Nullable<bool> _bWebApplicationUser;
		
		private System.Nullable<System.DateTime> _dEntryDate;
		
		private string _cJobTitle;
		
		private EntityRef<Department> _Department;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonIdChanging(decimal value);
    partial void OnPersonIdChanged();
    partial void OncDepCodeChanging(string value);
    partial void OncDepCodeChanged();
    partial void OncPsn_NumChanging(string value);
    partial void OncPsn_NumChanged();
    partial void OncPsn_NameChanging(string value);
    partial void OncPsn_NameChanged();
    partial void OndLeaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OndLeaveDateChanged();
    partial void OncLeaveResonChanging(string value);
    partial void OncLeaveResonChanged();
    partial void OncJobCodeChanging(string value);
    partial void OncJobCodeChanged();
    partial void OnJobNumberChanging(string value);
    partial void OnJobNumberChanged();
    partial void OncPersonBarCodeChanging(string value);
    partial void OncPersonBarCodeChanged();
    partial void OnrPersonTypeChanging(string value);
    partial void OnrPersonTypeChanged();
    partial void OncPsnMobilePhoneChanging(string value);
    partial void OncPsnMobilePhoneChanged();
    partial void OncPsnEmailChanging(string value);
    partial void OncPsnEmailChanged();
    partial void OncPsnQQCodeChanging(string value);
    partial void OncPsnQQCodeChanged();
    partial void OnnameCharFirstChanging(System.Nullable<char> value);
    partial void OnnameCharFirstChanged();
    partial void OnbHaveAccountChanging(System.Nullable<bool> value);
    partial void OnbHaveAccountChanged();
    partial void OnloginNameChanging(string value);
    partial void OnloginNameChanged();
    partial void OncHeadUrlChanging(string value);
    partial void OncHeadUrlChanged();
    partial void OncAsynTsChanging(string value);
    partial void OncAsynTsChanged();
    partial void OnAreaCodeChanging(string value);
    partial void OnAreaCodeChanged();
    partial void OnbPersonAppUserChanging(System.Nullable<bool> value);
    partial void OnbPersonAppUserChanged();
    partial void OnbWebApplicationUserChanging(System.Nullable<bool> value);
    partial void OnbWebApplicationUserChanged();
    partial void OndEntryDateChanging(System.Nullable<System.DateTime> value);
    partial void OndEntryDateChanged();
    partial void OncJobTitleChanging(string value);
    partial void OncJobTitleChanged();
    #endregion
		
		public Person()
		{
			this._Department = default(EntityRef<Department>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonId", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal PersonId
		{
			get
			{
				return this._PersonId;
			}
			set
			{
				if ((this._PersonId != value))
				{
					this.OnPersonIdChanging(value);
					this.SendPropertyChanging();
					this._PersonId = value;
					this.SendPropertyChanged("PersonId");
					this.OnPersonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDepCode", DbType="VarChar(50)")]
		public string cDepCode
		{
			get
			{
				return this._cDepCode;
			}
			set
			{
				if ((this._cDepCode != value))
				{
					if (this._Department.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncDepCodeChanging(value);
					this.SendPropertyChanging();
					this._cDepCode = value;
					this.SendPropertyChanged("cDepCode");
					this.OncDepCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPsn_Num", DbType="VarChar(50)")]
		public string cPsn_Num
		{
			get
			{
				return this._cPsn_Num;
			}
			set
			{
				if ((this._cPsn_Num != value))
				{
					this.OncPsn_NumChanging(value);
					this.SendPropertyChanging();
					this._cPsn_Num = value;
					this.SendPropertyChanged("cPsn_Num");
					this.OncPsn_NumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPsn_Name", DbType="NVarChar(50)")]
		public string cPsn_Name
		{
			get
			{
				return this._cPsn_Name;
			}
			set
			{
				if ((this._cPsn_Name != value))
				{
					this.OncPsn_NameChanging(value);
					this.SendPropertyChanging();
					this._cPsn_Name = value;
					this.SendPropertyChanged("cPsn_Name");
					this.OncPsn_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dLeaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dLeaveDate
		{
			get
			{
				return this._dLeaveDate;
			}
			set
			{
				if ((this._dLeaveDate != value))
				{
					this.OndLeaveDateChanging(value);
					this.SendPropertyChanging();
					this._dLeaveDate = value;
					this.SendPropertyChanged("dLeaveDate");
					this.OndLeaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cLeaveReson", DbType="NVarChar(400)")]
		public string cLeaveReson
		{
			get
			{
				return this._cLeaveReson;
			}
			set
			{
				if ((this._cLeaveReson != value))
				{
					this.OncLeaveResonChanging(value);
					this.SendPropertyChanging();
					this._cLeaveReson = value;
					this.SendPropertyChanged("cLeaveReson");
					this.OncLeaveResonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cJobCode", DbType="NVarChar(50)")]
		public string cJobCode
		{
			get
			{
				return this._cJobCode;
			}
			set
			{
				if ((this._cJobCode != value))
				{
					this.OncJobCodeChanging(value);
					this.SendPropertyChanging();
					this._cJobCode = value;
					this.SendPropertyChanged("cJobCode");
					this.OncJobCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobNumber", DbType="NVarChar(50)")]
		public string JobNumber
		{
			get
			{
				return this._JobNumber;
			}
			set
			{
				if ((this._JobNumber != value))
				{
					this.OnJobNumberChanging(value);
					this.SendPropertyChanging();
					this._JobNumber = value;
					this.SendPropertyChanged("JobNumber");
					this.OnJobNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPersonBarCode", DbType="NVarChar(60)")]
		public string cPersonBarCode
		{
			get
			{
				return this._cPersonBarCode;
			}
			set
			{
				if ((this._cPersonBarCode != value))
				{
					this.OncPersonBarCodeChanging(value);
					this.SendPropertyChanging();
					this._cPersonBarCode = value;
					this.SendPropertyChanged("cPersonBarCode");
					this.OncPersonBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rPersonType", DbType="VarChar(50)")]
		public string rPersonType
		{
			get
			{
				return this._rPersonType;
			}
			set
			{
				if ((this._rPersonType != value))
				{
					this.OnrPersonTypeChanging(value);
					this.SendPropertyChanging();
					this._rPersonType = value;
					this.SendPropertyChanged("rPersonType");
					this.OnrPersonTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPsnMobilePhone", DbType="VarChar(50)")]
		public string cPsnMobilePhone
		{
			get
			{
				return this._cPsnMobilePhone;
			}
			set
			{
				if ((this._cPsnMobilePhone != value))
				{
					this.OncPsnMobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._cPsnMobilePhone = value;
					this.SendPropertyChanged("cPsnMobilePhone");
					this.OncPsnMobilePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPsnEmail", DbType="VarChar(100)")]
		public string cPsnEmail
		{
			get
			{
				return this._cPsnEmail;
			}
			set
			{
				if ((this._cPsnEmail != value))
				{
					this.OncPsnEmailChanging(value);
					this.SendPropertyChanging();
					this._cPsnEmail = value;
					this.SendPropertyChanged("cPsnEmail");
					this.OncPsnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPsnQQCode", DbType="VarChar(50)")]
		public string cPsnQQCode
		{
			get
			{
				return this._cPsnQQCode;
			}
			set
			{
				if ((this._cPsnQQCode != value))
				{
					this.OncPsnQQCodeChanging(value);
					this.SendPropertyChanging();
					this._cPsnQQCode = value;
					this.SendPropertyChanged("cPsnQQCode");
					this.OncPsnQQCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameCharFirst", DbType="Char(1)")]
		public System.Nullable<char> nameCharFirst
		{
			get
			{
				return this._nameCharFirst;
			}
			set
			{
				if ((this._nameCharFirst != value))
				{
					this.OnnameCharFirstChanging(value);
					this.SendPropertyChanging();
					this._nameCharFirst = value;
					this.SendPropertyChanged("nameCharFirst");
					this.OnnameCharFirstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bHaveAccount", DbType="Bit")]
		public System.Nullable<bool> bHaveAccount
		{
			get
			{
				return this._bHaveAccount;
			}
			set
			{
				if ((this._bHaveAccount != value))
				{
					this.OnbHaveAccountChanging(value);
					this.SendPropertyChanging();
					this._bHaveAccount = value;
					this.SendPropertyChanged("bHaveAccount");
					this.OnbHaveAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginName", DbType="VarChar(50)")]
		public string loginName
		{
			get
			{
				return this._loginName;
			}
			set
			{
				if ((this._loginName != value))
				{
					this.OnloginNameChanging(value);
					this.SendPropertyChanging();
					this._loginName = value;
					this.SendPropertyChanged("loginName");
					this.OnloginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cHeadUrl", DbType="VarChar(500)")]
		public string cHeadUrl
		{
			get
			{
				return this._cHeadUrl;
			}
			set
			{
				if ((this._cHeadUrl != value))
				{
					this.OncHeadUrlChanging(value);
					this.SendPropertyChanging();
					this._cHeadUrl = value;
					this.SendPropertyChanged("cHeadUrl");
					this.OncHeadUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cAsynTs", DbType="VarChar(100)")]
		public string cAsynTs
		{
			get
			{
				return this._cAsynTs;
			}
			set
			{
				if ((this._cAsynTs != value))
				{
					this.OncAsynTsChanging(value);
					this.SendPropertyChanging();
					this._cAsynTs = value;
					this.SendPropertyChanged("cAsynTs");
					this.OncAsynTsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaCode", DbType="VarChar(50)")]
		public string AreaCode
		{
			get
			{
				return this._AreaCode;
			}
			set
			{
				if ((this._AreaCode != value))
				{
					this.OnAreaCodeChanging(value);
					this.SendPropertyChanging();
					this._AreaCode = value;
					this.SendPropertyChanged("AreaCode");
					this.OnAreaCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bPersonAppUser", DbType="Bit")]
		public System.Nullable<bool> bPersonAppUser
		{
			get
			{
				return this._bPersonAppUser;
			}
			set
			{
				if ((this._bPersonAppUser != value))
				{
					this.OnbPersonAppUserChanging(value);
					this.SendPropertyChanging();
					this._bPersonAppUser = value;
					this.SendPropertyChanged("bPersonAppUser");
					this.OnbPersonAppUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bWebApplicationUser", DbType="Bit")]
		public System.Nullable<bool> bWebApplicationUser
		{
			get
			{
				return this._bWebApplicationUser;
			}
			set
			{
				if ((this._bWebApplicationUser != value))
				{
					this.OnbWebApplicationUserChanging(value);
					this.SendPropertyChanging();
					this._bWebApplicationUser = value;
					this.SendPropertyChanged("bWebApplicationUser");
					this.OnbWebApplicationUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dEntryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dEntryDate
		{
			get
			{
				return this._dEntryDate;
			}
			set
			{
				if ((this._dEntryDate != value))
				{
					this.OndEntryDateChanging(value);
					this.SendPropertyChanging();
					this._dEntryDate = value;
					this.SendPropertyChanged("dEntryDate");
					this.OndEntryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cJobTitle", DbType="VarChar(50)")]
		public string cJobTitle
		{
			get
			{
				return this._cJobTitle;
			}
			set
			{
				if ((this._cJobTitle != value))
				{
					this.OncJobTitleChanging(value);
					this.SendPropertyChanging();
					this._cJobTitle = value;
					this.SendPropertyChanged("cJobTitle");
					this.OncJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Department_Person", Storage="_Department", ThisKey="cDepCode", OtherKey="cDepCode", IsForeignKey=true)]
		public Department Department
		{
			get
			{
				return this._Department.Entity;
			}
			set
			{
				Department previousValue = this._Department.Entity;
				if (((previousValue != value) 
							|| (this._Department.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Department.Entity = null;
						previousValue.Person.Remove(this);
					}
					this._Department.Entity = value;
					if ((value != null))
					{
						value.Person.Add(this);
						this._cDepCode = value.cDepCode;
					}
					else
					{
						this._cDepCode = default(string);
					}
					this.SendPropertyChanged("Department");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
