#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouHoo.DataBll
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UFDATA_001_2017")]
	public partial class ufdataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    #endregion
		
		public ufdataDataContext() : 
				base(global::YouHoo.DataBll.Properties.Settings.Default.UFDATA_001_2017ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ufdataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ufdataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ufdataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ufdataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customer
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cCusCode;
		
		private string _cCusName;
		
		private string _cCusAbbName;
		
		private string _cCCCode;
		
		private string _cDCCode;
		
		private string _cTrade;
		
		private string _cCusAddress;
		
		private string _cCusPostCode;
		
		private string _cCusRegCode;
		
		private string _cCusBank;
		
		private string _cCusAccount;
		
		private System.Nullable<System.DateTime> _dCusDevDate;
		
		private string _cCusLPerson;
		
		private string _cCusEmail;
		
		private string _cCusPerson;
		
		private string _cCusPhone;
		
		private string _cCusFax;
		
		private string _cCusBP;
		
		private string _cCusHand;
		
		private string _cCusPPerson;
		
		private System.Nullable<double> _iCusDisRate;
		
		private string _cCusCreGrade;
		
		private System.Nullable<double> _iCusCreLine;
		
		private System.Nullable<int> _iCusCreDate;
		
		private string _cCusPayCond;
		
		private string _cCusOAddress;
		
		private string _cCusOType;
		
		private string _cCusHeadCode;
		
		private string _cCusWhCode;
		
		private string _cCusDepart;
		
		private System.Nullable<double> _iARMoney;
		
		private System.Nullable<System.DateTime> _dLastDate;
		
		private System.Nullable<double> _iLastMoney;
		
		private System.Nullable<System.DateTime> _dLRDate;
		
		private System.Nullable<double> _iLRMoney;
		
		private System.Nullable<System.DateTime> _dEndDate;
		
		private System.Nullable<int> _iFrequency;
		
		private string _cCusDefine1;
		
		private string _cCusDefine2;
		
		private string _cCusDefine3;
		
		private System.Nullable<short> _iCostGrade;
		
		private string _cCreatePerson;
		
		private string _cModifyPerson;
		
		private System.Nullable<System.DateTime> _dModifyDate;
		
		private string _cRelVendor;
		
		private System.Nullable<int> _iId;
		
		private string _cPriceGroup;
		
		private string _cOfferGrade;
		
		private System.Nullable<double> _iOfferRate;
		
		private string _cCusDefine4;
		
		private string _cCusDefine5;
		
		private string _cCusDefine6;
		
		private string _cCusDefine7;
		
		private string _cCusDefine8;
		
		private string _cCusDefine9;
		
		private string _cCusDefine10;
		
		private System.Nullable<int> _cCusDefine11;
		
		private System.Nullable<int> _cCusDefine12;
		
		private System.Nullable<double> _cCusDefine13;
		
		private System.Nullable<double> _cCusDefine14;
		
		private System.Nullable<System.DateTime> _cCusDefine15;
		
		private System.Nullable<System.DateTime> _cCusDefine16;
		
		private System.Data.Linq.Binary _pubufts;
		
		private string _cInvoiceCompany;
		
		private bool _bCredit;
		
		private bool _bCreditDate;
		
		private bool _bCreditByHead;
		
		private bool _bLicenceDate;
		
		private System.Nullable<System.DateTime> _dLicenceSDate;
		
		private System.Nullable<System.DateTime> _dLicenceEDate;
		
		private System.Nullable<int> _iLicenceADays;
		
		private bool _bBusinessDate;
		
		private System.Nullable<System.DateTime> _dBusinessSDate;
		
		private System.Nullable<System.DateTime> _dBusinessEDate;
		
		private System.Nullable<int> _iBusinessADays;
		
		private bool _bProxy;
		
		private System.Nullable<System.DateTime> _dProxySDate;
		
		private System.Nullable<System.DateTime> _dProxyEDate;
		
		private System.Nullable<int> _iProxyADays;
		
		private string _cMemo;
		
		private bool _bLimitSale;
		
		private System.Nullable<System.Guid> _cCusContactCode;
		
		private string _cCusCountryCode;
		
		private string _cCusEnName;
		
		private string _cCusEnAddr1;
		
		private string _cCusEnAddr2;
		
		private string _cCusEnAddr3;
		
		private string _cCusEnAddr4;
		
		private string _cCusPortCode;
		
		private string _cPrimaryVen;
		
		private System.Nullable<double> _fCommisionRate;
		
		private System.Nullable<double> _fInsueRate;
		
		private bool _bHomeBranch;
		
		private string _cBranchAddr;
		
		private string _cBranchPhone;
		
		private string _cBranchPerson;
		
		private string _cCusTradeCCode;
		
		private string _CustomerKCode;
		
		private bool _bCusState;
		
		private bool _bShop;
		
		private string _cCusBankCode;
		
		private string _cCusExch_name;
		
		private short _iCusGSPType;
		
		private System.Nullable<short> _iCusGSPAuth;
		
		private string _cCusGSPAuthNo;
		
		private string _cCusBusinessNo;
		
		private string _cCusLicenceNo;
		
		private bool _bCusDomestic;
		
		private bool _bCusOverseas;
		
		private string _cCusCreditCompany;
		
		private string _cCusSAProtocol;
		
		private string _cCusExProtocol;
		
		private string _cCusOtherProtocol;
		
		private System.Nullable<double> _fCusDiscountRate;
		
		private string _cCusSSCode;
		
		private string _cCusCMProtocol;
		
		private System.DateTime _dCusCreateDatetime;
		
		private string _cCusAppDocNo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncCusCodeChanging(string value);
    partial void OncCusCodeChanged();
    partial void OncCusNameChanging(string value);
    partial void OncCusNameChanged();
    partial void OncCusAbbNameChanging(string value);
    partial void OncCusAbbNameChanged();
    partial void OncCCCodeChanging(string value);
    partial void OncCCCodeChanged();
    partial void OncDCCodeChanging(string value);
    partial void OncDCCodeChanged();
    partial void OncTradeChanging(string value);
    partial void OncTradeChanged();
    partial void OncCusAddressChanging(string value);
    partial void OncCusAddressChanged();
    partial void OncCusPostCodeChanging(string value);
    partial void OncCusPostCodeChanged();
    partial void OncCusRegCodeChanging(string value);
    partial void OncCusRegCodeChanged();
    partial void OncCusBankChanging(string value);
    partial void OncCusBankChanged();
    partial void OncCusAccountChanging(string value);
    partial void OncCusAccountChanged();
    partial void OndCusDevDateChanging(System.Nullable<System.DateTime> value);
    partial void OndCusDevDateChanged();
    partial void OncCusLPersonChanging(string value);
    partial void OncCusLPersonChanged();
    partial void OncCusEmailChanging(string value);
    partial void OncCusEmailChanged();
    partial void OncCusPersonChanging(string value);
    partial void OncCusPersonChanged();
    partial void OncCusPhoneChanging(string value);
    partial void OncCusPhoneChanged();
    partial void OncCusFaxChanging(string value);
    partial void OncCusFaxChanged();
    partial void OncCusBPChanging(string value);
    partial void OncCusBPChanged();
    partial void OncCusHandChanging(string value);
    partial void OncCusHandChanged();
    partial void OncCusPPersonChanging(string value);
    partial void OncCusPPersonChanged();
    partial void OniCusDisRateChanging(System.Nullable<double> value);
    partial void OniCusDisRateChanged();
    partial void OncCusCreGradeChanging(string value);
    partial void OncCusCreGradeChanged();
    partial void OniCusCreLineChanging(System.Nullable<double> value);
    partial void OniCusCreLineChanged();
    partial void OniCusCreDateChanging(System.Nullable<int> value);
    partial void OniCusCreDateChanged();
    partial void OncCusPayCondChanging(string value);
    partial void OncCusPayCondChanged();
    partial void OncCusOAddressChanging(string value);
    partial void OncCusOAddressChanged();
    partial void OncCusOTypeChanging(string value);
    partial void OncCusOTypeChanged();
    partial void OncCusHeadCodeChanging(string value);
    partial void OncCusHeadCodeChanged();
    partial void OncCusWhCodeChanging(string value);
    partial void OncCusWhCodeChanged();
    partial void OncCusDepartChanging(string value);
    partial void OncCusDepartChanged();
    partial void OniARMoneyChanging(System.Nullable<double> value);
    partial void OniARMoneyChanged();
    partial void OndLastDateChanging(System.Nullable<System.DateTime> value);
    partial void OndLastDateChanged();
    partial void OniLastMoneyChanging(System.Nullable<double> value);
    partial void OniLastMoneyChanged();
    partial void OndLRDateChanging(System.Nullable<System.DateTime> value);
    partial void OndLRDateChanged();
    partial void OniLRMoneyChanging(System.Nullable<double> value);
    partial void OniLRMoneyChanged();
    partial void OndEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OndEndDateChanged();
    partial void OniFrequencyChanging(System.Nullable<int> value);
    partial void OniFrequencyChanged();
    partial void OncCusDefine1Changing(string value);
    partial void OncCusDefine1Changed();
    partial void OncCusDefine2Changing(string value);
    partial void OncCusDefine2Changed();
    partial void OncCusDefine3Changing(string value);
    partial void OncCusDefine3Changed();
    partial void OniCostGradeChanging(System.Nullable<short> value);
    partial void OniCostGradeChanged();
    partial void OncCreatePersonChanging(string value);
    partial void OncCreatePersonChanged();
    partial void OncModifyPersonChanging(string value);
    partial void OncModifyPersonChanged();
    partial void OndModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OndModifyDateChanged();
    partial void OncRelVendorChanging(string value);
    partial void OncRelVendorChanged();
    partial void OniIdChanging(System.Nullable<int> value);
    partial void OniIdChanged();
    partial void OncPriceGroupChanging(string value);
    partial void OncPriceGroupChanged();
    partial void OncOfferGradeChanging(string value);
    partial void OncOfferGradeChanged();
    partial void OniOfferRateChanging(System.Nullable<double> value);
    partial void OniOfferRateChanged();
    partial void OncCusDefine4Changing(string value);
    partial void OncCusDefine4Changed();
    partial void OncCusDefine5Changing(string value);
    partial void OncCusDefine5Changed();
    partial void OncCusDefine6Changing(string value);
    partial void OncCusDefine6Changed();
    partial void OncCusDefine7Changing(string value);
    partial void OncCusDefine7Changed();
    partial void OncCusDefine8Changing(string value);
    partial void OncCusDefine8Changed();
    partial void OncCusDefine9Changing(string value);
    partial void OncCusDefine9Changed();
    partial void OncCusDefine10Changing(string value);
    partial void OncCusDefine10Changed();
    partial void OncCusDefine11Changing(System.Nullable<int> value);
    partial void OncCusDefine11Changed();
    partial void OncCusDefine12Changing(System.Nullable<int> value);
    partial void OncCusDefine12Changed();
    partial void OncCusDefine13Changing(System.Nullable<double> value);
    partial void OncCusDefine13Changed();
    partial void OncCusDefine14Changing(System.Nullable<double> value);
    partial void OncCusDefine14Changed();
    partial void OncCusDefine15Changing(System.Nullable<System.DateTime> value);
    partial void OncCusDefine15Changed();
    partial void OncCusDefine16Changing(System.Nullable<System.DateTime> value);
    partial void OncCusDefine16Changed();
    partial void OnpubuftsChanging(System.Data.Linq.Binary value);
    partial void OnpubuftsChanged();
    partial void OncInvoiceCompanyChanging(string value);
    partial void OncInvoiceCompanyChanged();
    partial void OnbCreditChanging(bool value);
    partial void OnbCreditChanged();
    partial void OnbCreditDateChanging(bool value);
    partial void OnbCreditDateChanged();
    partial void OnbCreditByHeadChanging(bool value);
    partial void OnbCreditByHeadChanged();
    partial void OnbLicenceDateChanging(bool value);
    partial void OnbLicenceDateChanged();
    partial void OndLicenceSDateChanging(System.Nullable<System.DateTime> value);
    partial void OndLicenceSDateChanged();
    partial void OndLicenceEDateChanging(System.Nullable<System.DateTime> value);
    partial void OndLicenceEDateChanged();
    partial void OniLicenceADaysChanging(System.Nullable<int> value);
    partial void OniLicenceADaysChanged();
    partial void OnbBusinessDateChanging(bool value);
    partial void OnbBusinessDateChanged();
    partial void OndBusinessSDateChanging(System.Nullable<System.DateTime> value);
    partial void OndBusinessSDateChanged();
    partial void OndBusinessEDateChanging(System.Nullable<System.DateTime> value);
    partial void OndBusinessEDateChanged();
    partial void OniBusinessADaysChanging(System.Nullable<int> value);
    partial void OniBusinessADaysChanged();
    partial void OnbProxyChanging(bool value);
    partial void OnbProxyChanged();
    partial void OndProxySDateChanging(System.Nullable<System.DateTime> value);
    partial void OndProxySDateChanged();
    partial void OndProxyEDateChanging(System.Nullable<System.DateTime> value);
    partial void OndProxyEDateChanged();
    partial void OniProxyADaysChanging(System.Nullable<int> value);
    partial void OniProxyADaysChanged();
    partial void OncMemoChanging(string value);
    partial void OncMemoChanged();
    partial void OnbLimitSaleChanging(bool value);
    partial void OnbLimitSaleChanged();
    partial void OncCusContactCodeChanging(System.Nullable<System.Guid> value);
    partial void OncCusContactCodeChanged();
    partial void OncCusCountryCodeChanging(string value);
    partial void OncCusCountryCodeChanged();
    partial void OncCusEnNameChanging(string value);
    partial void OncCusEnNameChanged();
    partial void OncCusEnAddr1Changing(string value);
    partial void OncCusEnAddr1Changed();
    partial void OncCusEnAddr2Changing(string value);
    partial void OncCusEnAddr2Changed();
    partial void OncCusEnAddr3Changing(string value);
    partial void OncCusEnAddr3Changed();
    partial void OncCusEnAddr4Changing(string value);
    partial void OncCusEnAddr4Changed();
    partial void OncCusPortCodeChanging(string value);
    partial void OncCusPortCodeChanged();
    partial void OncPrimaryVenChanging(string value);
    partial void OncPrimaryVenChanged();
    partial void OnfCommisionRateChanging(System.Nullable<double> value);
    partial void OnfCommisionRateChanged();
    partial void OnfInsueRateChanging(System.Nullable<double> value);
    partial void OnfInsueRateChanged();
    partial void OnbHomeBranchChanging(bool value);
    partial void OnbHomeBranchChanged();
    partial void OncBranchAddrChanging(string value);
    partial void OncBranchAddrChanged();
    partial void OncBranchPhoneChanging(string value);
    partial void OncBranchPhoneChanged();
    partial void OncBranchPersonChanging(string value);
    partial void OncBranchPersonChanged();
    partial void OncCusTradeCCodeChanging(string value);
    partial void OncCusTradeCCodeChanged();
    partial void OnCustomerKCodeChanging(string value);
    partial void OnCustomerKCodeChanged();
    partial void OnbCusStateChanging(bool value);
    partial void OnbCusStateChanged();
    partial void OnbShopChanging(bool value);
    partial void OnbShopChanged();
    partial void OncCusBankCodeChanging(string value);
    partial void OncCusBankCodeChanged();
    partial void OncCusExch_nameChanging(string value);
    partial void OncCusExch_nameChanged();
    partial void OniCusGSPTypeChanging(short value);
    partial void OniCusGSPTypeChanged();
    partial void OniCusGSPAuthChanging(System.Nullable<short> value);
    partial void OniCusGSPAuthChanged();
    partial void OncCusGSPAuthNoChanging(string value);
    partial void OncCusGSPAuthNoChanged();
    partial void OncCusBusinessNoChanging(string value);
    partial void OncCusBusinessNoChanged();
    partial void OncCusLicenceNoChanging(string value);
    partial void OncCusLicenceNoChanged();
    partial void OnbCusDomesticChanging(bool value);
    partial void OnbCusDomesticChanged();
    partial void OnbCusOverseasChanging(bool value);
    partial void OnbCusOverseasChanged();
    partial void OncCusCreditCompanyChanging(string value);
    partial void OncCusCreditCompanyChanged();
    partial void OncCusSAProtocolChanging(string value);
    partial void OncCusSAProtocolChanged();
    partial void OncCusExProtocolChanging(string value);
    partial void OncCusExProtocolChanged();
    partial void OncCusOtherProtocolChanging(string value);
    partial void OncCusOtherProtocolChanged();
    partial void OnfCusDiscountRateChanging(System.Nullable<double> value);
    partial void OnfCusDiscountRateChanged();
    partial void OncCusSSCodeChanging(string value);
    partial void OncCusSSCodeChanged();
    partial void OncCusCMProtocolChanging(string value);
    partial void OncCusCMProtocolChanged();
    partial void OndCusCreateDatetimeChanging(System.DateTime value);
    partial void OndCusCreateDatetimeChanged();
    partial void OncCusAppDocNoChanging(string value);
    partial void OncCusAppDocNoChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string cCusCode
		{
			get
			{
				return this._cCusCode;
			}
			set
			{
				if ((this._cCusCode != value))
				{
					this.OncCusCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusCode = value;
					this.SendPropertyChanged("cCusCode");
					this.OncCusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusName", DbType="NVarChar(98)", UpdateCheck=UpdateCheck.Never)]
		public string cCusName
		{
			get
			{
				return this._cCusName;
			}
			set
			{
				if ((this._cCusName != value))
				{
					this.OncCusNameChanging(value);
					this.SendPropertyChanging();
					this._cCusName = value;
					this.SendPropertyChanged("cCusName");
					this.OncCusNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusAbbName", DbType="NVarChar(60) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string cCusAbbName
		{
			get
			{
				return this._cCusAbbName;
			}
			set
			{
				if ((this._cCusAbbName != value))
				{
					this.OncCusAbbNameChanging(value);
					this.SendPropertyChanging();
					this._cCusAbbName = value;
					this.SendPropertyChanged("cCusAbbName");
					this.OncCusAbbNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCCCode", DbType="NVarChar(12)", UpdateCheck=UpdateCheck.Never)]
		public string cCCCode
		{
			get
			{
				return this._cCCCode;
			}
			set
			{
				if ((this._cCCCode != value))
				{
					this.OncCCCodeChanging(value);
					this.SendPropertyChanging();
					this._cCCCode = value;
					this.SendPropertyChanged("cCCCode");
					this.OncCCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDCCode", DbType="NVarChar(12)", UpdateCheck=UpdateCheck.Never)]
		public string cDCCode
		{
			get
			{
				return this._cDCCode;
			}
			set
			{
				if ((this._cDCCode != value))
				{
					this.OncDCCodeChanging(value);
					this.SendPropertyChanging();
					this._cDCCode = value;
					this.SendPropertyChanged("cDCCode");
					this.OncDCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cTrade", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cTrade
		{
			get
			{
				return this._cTrade;
			}
			set
			{
				if ((this._cTrade != value))
				{
					this.OncTradeChanging(value);
					this.SendPropertyChanging();
					this._cTrade = value;
					this.SendPropertyChanged("cTrade");
					this.OncTradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusAddress", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string cCusAddress
		{
			get
			{
				return this._cCusAddress;
			}
			set
			{
				if ((this._cCusAddress != value))
				{
					this.OncCusAddressChanging(value);
					this.SendPropertyChanging();
					this._cCusAddress = value;
					this.SendPropertyChanged("cCusAddress");
					this.OncCusAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusPostCode", DbType="NVarChar(6)", UpdateCheck=UpdateCheck.Never)]
		public string cCusPostCode
		{
			get
			{
				return this._cCusPostCode;
			}
			set
			{
				if ((this._cCusPostCode != value))
				{
					this.OncCusPostCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusPostCode = value;
					this.SendPropertyChanged("cCusPostCode");
					this.OncCusPostCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusRegCode", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cCusRegCode
		{
			get
			{
				return this._cCusRegCode;
			}
			set
			{
				if ((this._cCusRegCode != value))
				{
					this.OncCusRegCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusRegCode = value;
					this.SendPropertyChanged("cCusRegCode");
					this.OncCusRegCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusBank", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string cCusBank
		{
			get
			{
				return this._cCusBank;
			}
			set
			{
				if ((this._cCusBank != value))
				{
					this.OncCusBankChanging(value);
					this.SendPropertyChanging();
					this._cCusBank = value;
					this.SendPropertyChanged("cCusBank");
					this.OncCusBankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusAccount", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cCusAccount
		{
			get
			{
				return this._cCusAccount;
			}
			set
			{
				if ((this._cCusAccount != value))
				{
					this.OncCusAccountChanging(value);
					this.SendPropertyChanging();
					this._cCusAccount = value;
					this.SendPropertyChanged("cCusAccount");
					this.OncCusAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dCusDevDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dCusDevDate
		{
			get
			{
				return this._dCusDevDate;
			}
			set
			{
				if ((this._dCusDevDate != value))
				{
					this.OndCusDevDateChanging(value);
					this.SendPropertyChanging();
					this._dCusDevDate = value;
					this.SendPropertyChanged("dCusDevDate");
					this.OndCusDevDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusLPerson", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string cCusLPerson
		{
			get
			{
				return this._cCusLPerson;
			}
			set
			{
				if ((this._cCusLPerson != value))
				{
					this.OncCusLPersonChanging(value);
					this.SendPropertyChanging();
					this._cCusLPerson = value;
					this.SendPropertyChanged("cCusLPerson");
					this.OncCusLPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusEmail", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string cCusEmail
		{
			get
			{
				return this._cCusEmail;
			}
			set
			{
				if ((this._cCusEmail != value))
				{
					this.OncCusEmailChanging(value);
					this.SendPropertyChanging();
					this._cCusEmail = value;
					this.SendPropertyChanged("cCusEmail");
					this.OncCusEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusPerson", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cCusPerson
		{
			get
			{
				return this._cCusPerson;
			}
			set
			{
				if ((this._cCusPerson != value))
				{
					this.OncCusPersonChanging(value);
					this.SendPropertyChanging();
					this._cCusPerson = value;
					this.SendPropertyChanged("cCusPerson");
					this.OncCusPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusPhone", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string cCusPhone
		{
			get
			{
				return this._cCusPhone;
			}
			set
			{
				if ((this._cCusPhone != value))
				{
					this.OncCusPhoneChanging(value);
					this.SendPropertyChanging();
					this._cCusPhone = value;
					this.SendPropertyChanged("cCusPhone");
					this.OncCusPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusFax", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string cCusFax
		{
			get
			{
				return this._cCusFax;
			}
			set
			{
				if ((this._cCusFax != value))
				{
					this.OncCusFaxChanging(value);
					this.SendPropertyChanging();
					this._cCusFax = value;
					this.SendPropertyChanged("cCusFax");
					this.OncCusFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusBP", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusBP
		{
			get
			{
				return this._cCusBP;
			}
			set
			{
				if ((this._cCusBP != value))
				{
					this.OncCusBPChanging(value);
					this.SendPropertyChanging();
					this._cCusBP = value;
					this.SendPropertyChanged("cCusBP");
					this.OncCusBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusHand", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusHand
		{
			get
			{
				return this._cCusHand;
			}
			set
			{
				if ((this._cCusHand != value))
				{
					this.OncCusHandChanging(value);
					this.SendPropertyChanging();
					this._cCusHand = value;
					this.SendPropertyChanged("cCusHand");
					this.OncCusHandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusPPerson", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusPPerson
		{
			get
			{
				return this._cCusPPerson;
			}
			set
			{
				if ((this._cCusPPerson != value))
				{
					this.OncCusPPersonChanging(value);
					this.SendPropertyChanging();
					this._cCusPPerson = value;
					this.SendPropertyChanged("cCusPPerson");
					this.OncCusPPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCusDisRate", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> iCusDisRate
		{
			get
			{
				return this._iCusDisRate;
			}
			set
			{
				if ((this._iCusDisRate != value))
				{
					this.OniCusDisRateChanging(value);
					this.SendPropertyChanging();
					this._iCusDisRate = value;
					this.SendPropertyChanged("iCusDisRate");
					this.OniCusDisRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusCreGrade", DbType="NVarChar(6)", UpdateCheck=UpdateCheck.Never)]
		public string cCusCreGrade
		{
			get
			{
				return this._cCusCreGrade;
			}
			set
			{
				if ((this._cCusCreGrade != value))
				{
					this.OncCusCreGradeChanging(value);
					this.SendPropertyChanging();
					this._cCusCreGrade = value;
					this.SendPropertyChanged("cCusCreGrade");
					this.OncCusCreGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCusCreLine", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> iCusCreLine
		{
			get
			{
				return this._iCusCreLine;
			}
			set
			{
				if ((this._iCusCreLine != value))
				{
					this.OniCusCreLineChanging(value);
					this.SendPropertyChanging();
					this._iCusCreLine = value;
					this.SendPropertyChanged("iCusCreLine");
					this.OniCusCreLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCusCreDate", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> iCusCreDate
		{
			get
			{
				return this._iCusCreDate;
			}
			set
			{
				if ((this._iCusCreDate != value))
				{
					this.OniCusCreDateChanging(value);
					this.SendPropertyChanging();
					this._iCusCreDate = value;
					this.SendPropertyChanged("iCusCreDate");
					this.OniCusCreDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusPayCond", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusPayCond
		{
			get
			{
				return this._cCusPayCond;
			}
			set
			{
				if ((this._cCusPayCond != value))
				{
					this.OncCusPayCondChanging(value);
					this.SendPropertyChanging();
					this._cCusPayCond = value;
					this.SendPropertyChanged("cCusPayCond");
					this.OncCusPayCondChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusOAddress", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string cCusOAddress
		{
			get
			{
				return this._cCusOAddress;
			}
			set
			{
				if ((this._cCusOAddress != value))
				{
					this.OncCusOAddressChanging(value);
					this.SendPropertyChanging();
					this._cCusOAddress = value;
					this.SendPropertyChanged("cCusOAddress");
					this.OncCusOAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusOType", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string cCusOType
		{
			get
			{
				return this._cCusOType;
			}
			set
			{
				if ((this._cCusOType != value))
				{
					this.OncCusOTypeChanging(value);
					this.SendPropertyChanging();
					this._cCusOType = value;
					this.SendPropertyChanged("cCusOType");
					this.OncCusOTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusHeadCode", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusHeadCode
		{
			get
			{
				return this._cCusHeadCode;
			}
			set
			{
				if ((this._cCusHeadCode != value))
				{
					this.OncCusHeadCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusHeadCode = value;
					this.SendPropertyChanged("cCusHeadCode");
					this.OncCusHeadCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusWhCode", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string cCusWhCode
		{
			get
			{
				return this._cCusWhCode;
			}
			set
			{
				if ((this._cCusWhCode != value))
				{
					this.OncCusWhCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusWhCode = value;
					this.SendPropertyChanged("cCusWhCode");
					this.OncCusWhCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDepart", DbType="NVarChar(12)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDepart
		{
			get
			{
				return this._cCusDepart;
			}
			set
			{
				if ((this._cCusDepart != value))
				{
					this.OncCusDepartChanging(value);
					this.SendPropertyChanging();
					this._cCusDepart = value;
					this.SendPropertyChanged("cCusDepart");
					this.OncCusDepartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iARMoney", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> iARMoney
		{
			get
			{
				return this._iARMoney;
			}
			set
			{
				if ((this._iARMoney != value))
				{
					this.OniARMoneyChanging(value);
					this.SendPropertyChanging();
					this._iARMoney = value;
					this.SendPropertyChanged("iARMoney");
					this.OniARMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dLastDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dLastDate
		{
			get
			{
				return this._dLastDate;
			}
			set
			{
				if ((this._dLastDate != value))
				{
					this.OndLastDateChanging(value);
					this.SendPropertyChanging();
					this._dLastDate = value;
					this.SendPropertyChanged("dLastDate");
					this.OndLastDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLastMoney", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> iLastMoney
		{
			get
			{
				return this._iLastMoney;
			}
			set
			{
				if ((this._iLastMoney != value))
				{
					this.OniLastMoneyChanging(value);
					this.SendPropertyChanging();
					this._iLastMoney = value;
					this.SendPropertyChanged("iLastMoney");
					this.OniLastMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dLRDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dLRDate
		{
			get
			{
				return this._dLRDate;
			}
			set
			{
				if ((this._dLRDate != value))
				{
					this.OndLRDateChanging(value);
					this.SendPropertyChanging();
					this._dLRDate = value;
					this.SendPropertyChanged("dLRDate");
					this.OndLRDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLRMoney", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> iLRMoney
		{
			get
			{
				return this._iLRMoney;
			}
			set
			{
				if ((this._iLRMoney != value))
				{
					this.OniLRMoneyChanging(value);
					this.SendPropertyChanging();
					this._iLRMoney = value;
					this.SendPropertyChanged("iLRMoney");
					this.OniLRMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dEndDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dEndDate
		{
			get
			{
				return this._dEndDate;
			}
			set
			{
				if ((this._dEndDate != value))
				{
					this.OndEndDateChanging(value);
					this.SendPropertyChanging();
					this._dEndDate = value;
					this.SendPropertyChanged("dEndDate");
					this.OndEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iFrequency", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> iFrequency
		{
			get
			{
				return this._iFrequency;
			}
			set
			{
				if ((this._iFrequency != value))
				{
					this.OniFrequencyChanging(value);
					this.SendPropertyChanging();
					this._iFrequency = value;
					this.SendPropertyChanged("iFrequency");
					this.OniFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine1", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine1
		{
			get
			{
				return this._cCusDefine1;
			}
			set
			{
				if ((this._cCusDefine1 != value))
				{
					this.OncCusDefine1Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine1 = value;
					this.SendPropertyChanged("cCusDefine1");
					this.OncCusDefine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine2", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine2
		{
			get
			{
				return this._cCusDefine2;
			}
			set
			{
				if ((this._cCusDefine2 != value))
				{
					this.OncCusDefine2Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine2 = value;
					this.SendPropertyChanged("cCusDefine2");
					this.OncCusDefine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine3", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine3
		{
			get
			{
				return this._cCusDefine3;
			}
			set
			{
				if ((this._cCusDefine3 != value))
				{
					this.OncCusDefine3Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine3 = value;
					this.SendPropertyChanged("cCusDefine3");
					this.OncCusDefine3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCostGrade", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> iCostGrade
		{
			get
			{
				return this._iCostGrade;
			}
			set
			{
				if ((this._iCostGrade != value))
				{
					this.OniCostGradeChanging(value);
					this.SendPropertyChanging();
					this._iCostGrade = value;
					this.SendPropertyChanged("iCostGrade");
					this.OniCostGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCreatePerson", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCreatePerson
		{
			get
			{
				return this._cCreatePerson;
			}
			set
			{
				if ((this._cCreatePerson != value))
				{
					this.OncCreatePersonChanging(value);
					this.SendPropertyChanging();
					this._cCreatePerson = value;
					this.SendPropertyChanged("cCreatePerson");
					this.OncCreatePersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cModifyPerson", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cModifyPerson
		{
			get
			{
				return this._cModifyPerson;
			}
			set
			{
				if ((this._cModifyPerson != value))
				{
					this.OncModifyPersonChanging(value);
					this.SendPropertyChanging();
					this._cModifyPerson = value;
					this.SendPropertyChanged("cModifyPerson");
					this.OncModifyPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dModifyDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dModifyDate
		{
			get
			{
				return this._dModifyDate;
			}
			set
			{
				if ((this._dModifyDate != value))
				{
					this.OndModifyDateChanging(value);
					this.SendPropertyChanging();
					this._dModifyDate = value;
					this.SendPropertyChanged("dModifyDate");
					this.OndModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cRelVendor", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cRelVendor
		{
			get
			{
				return this._cRelVendor;
			}
			set
			{
				if ((this._cRelVendor != value))
				{
					this.OncRelVendorChanging(value);
					this.SendPropertyChanging();
					this._cRelVendor = value;
					this.SendPropertyChanged("cRelVendor");
					this.OncRelVendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> iId
		{
			get
			{
				return this._iId;
			}
			set
			{
				if ((this._iId != value))
				{
					this.OniIdChanging(value);
					this.SendPropertyChanging();
					this._iId = value;
					this.SendPropertyChanged("iId");
					this.OniIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPriceGroup", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cPriceGroup
		{
			get
			{
				return this._cPriceGroup;
			}
			set
			{
				if ((this._cPriceGroup != value))
				{
					this.OncPriceGroupChanging(value);
					this.SendPropertyChanging();
					this._cPriceGroup = value;
					this.SendPropertyChanged("cPriceGroup");
					this.OncPriceGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cOfferGrade", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cOfferGrade
		{
			get
			{
				return this._cOfferGrade;
			}
			set
			{
				if ((this._cOfferGrade != value))
				{
					this.OncOfferGradeChanging(value);
					this.SendPropertyChanging();
					this._cOfferGrade = value;
					this.SendPropertyChanged("cOfferGrade");
					this.OncOfferGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iOfferRate", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> iOfferRate
		{
			get
			{
				return this._iOfferRate;
			}
			set
			{
				if ((this._iOfferRate != value))
				{
					this.OniOfferRateChanging(value);
					this.SendPropertyChanging();
					this._iOfferRate = value;
					this.SendPropertyChanged("iOfferRate");
					this.OniOfferRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine4", DbType="NVarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine4
		{
			get
			{
				return this._cCusDefine4;
			}
			set
			{
				if ((this._cCusDefine4 != value))
				{
					this.OncCusDefine4Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine4 = value;
					this.SendPropertyChanged("cCusDefine4");
					this.OncCusDefine4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine5", DbType="NVarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine5
		{
			get
			{
				return this._cCusDefine5;
			}
			set
			{
				if ((this._cCusDefine5 != value))
				{
					this.OncCusDefine5Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine5 = value;
					this.SendPropertyChanged("cCusDefine5");
					this.OncCusDefine5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine6", DbType="NVarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine6
		{
			get
			{
				return this._cCusDefine6;
			}
			set
			{
				if ((this._cCusDefine6 != value))
				{
					this.OncCusDefine6Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine6 = value;
					this.SendPropertyChanged("cCusDefine6");
					this.OncCusDefine6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine7", DbType="NVarChar(120)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine7
		{
			get
			{
				return this._cCusDefine7;
			}
			set
			{
				if ((this._cCusDefine7 != value))
				{
					this.OncCusDefine7Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine7 = value;
					this.SendPropertyChanged("cCusDefine7");
					this.OncCusDefine7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine8", DbType="NVarChar(120)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine8
		{
			get
			{
				return this._cCusDefine8;
			}
			set
			{
				if ((this._cCusDefine8 != value))
				{
					this.OncCusDefine8Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine8 = value;
					this.SendPropertyChanged("cCusDefine8");
					this.OncCusDefine8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine9", DbType="NVarChar(120)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine9
		{
			get
			{
				return this._cCusDefine9;
			}
			set
			{
				if ((this._cCusDefine9 != value))
				{
					this.OncCusDefine9Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine9 = value;
					this.SendPropertyChanged("cCusDefine9");
					this.OncCusDefine9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine10", DbType="NVarChar(120)", UpdateCheck=UpdateCheck.Never)]
		public string cCusDefine10
		{
			get
			{
				return this._cCusDefine10;
			}
			set
			{
				if ((this._cCusDefine10 != value))
				{
					this.OncCusDefine10Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine10 = value;
					this.SendPropertyChanged("cCusDefine10");
					this.OncCusDefine10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine11", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> cCusDefine11
		{
			get
			{
				return this._cCusDefine11;
			}
			set
			{
				if ((this._cCusDefine11 != value))
				{
					this.OncCusDefine11Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine11 = value;
					this.SendPropertyChanged("cCusDefine11");
					this.OncCusDefine11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine12", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> cCusDefine12
		{
			get
			{
				return this._cCusDefine12;
			}
			set
			{
				if ((this._cCusDefine12 != value))
				{
					this.OncCusDefine12Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine12 = value;
					this.SendPropertyChanged("cCusDefine12");
					this.OncCusDefine12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine13", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> cCusDefine13
		{
			get
			{
				return this._cCusDefine13;
			}
			set
			{
				if ((this._cCusDefine13 != value))
				{
					this.OncCusDefine13Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine13 = value;
					this.SendPropertyChanged("cCusDefine13");
					this.OncCusDefine13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine14", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> cCusDefine14
		{
			get
			{
				return this._cCusDefine14;
			}
			set
			{
				if ((this._cCusDefine14 != value))
				{
					this.OncCusDefine14Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine14 = value;
					this.SendPropertyChanged("cCusDefine14");
					this.OncCusDefine14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine15", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> cCusDefine15
		{
			get
			{
				return this._cCusDefine15;
			}
			set
			{
				if ((this._cCusDefine15 != value))
				{
					this.OncCusDefine15Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine15 = value;
					this.SendPropertyChanged("cCusDefine15");
					this.OncCusDefine15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusDefine16", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> cCusDefine16
		{
			get
			{
				return this._cCusDefine16;
			}
			set
			{
				if ((this._cCusDefine16 != value))
				{
					this.OncCusDefine16Changing(value);
					this.SendPropertyChanging();
					this._cCusDefine16 = value;
					this.SendPropertyChanged("cCusDefine16");
					this.OncCusDefine16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pubufts", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary pubufts
		{
			get
			{
				return this._pubufts;
			}
			set
			{
				if ((this._pubufts != value))
				{
					this.OnpubuftsChanging(value);
					this.SendPropertyChanging();
					this._pubufts = value;
					this.SendPropertyChanged("pubufts");
					this.OnpubuftsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cInvoiceCompany", DbType="NVarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string cInvoiceCompany
		{
			get
			{
				return this._cInvoiceCompany;
			}
			set
			{
				if ((this._cInvoiceCompany != value))
				{
					this.OncInvoiceCompanyChanging(value);
					this.SendPropertyChanging();
					this._cInvoiceCompany = value;
					this.SendPropertyChanged("cInvoiceCompany");
					this.OncInvoiceCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bCredit", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bCredit
		{
			get
			{
				return this._bCredit;
			}
			set
			{
				if ((this._bCredit != value))
				{
					this.OnbCreditChanging(value);
					this.SendPropertyChanging();
					this._bCredit = value;
					this.SendPropertyChanged("bCredit");
					this.OnbCreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bCreditDate", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bCreditDate
		{
			get
			{
				return this._bCreditDate;
			}
			set
			{
				if ((this._bCreditDate != value))
				{
					this.OnbCreditDateChanging(value);
					this.SendPropertyChanging();
					this._bCreditDate = value;
					this.SendPropertyChanged("bCreditDate");
					this.OnbCreditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bCreditByHead", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bCreditByHead
		{
			get
			{
				return this._bCreditByHead;
			}
			set
			{
				if ((this._bCreditByHead != value))
				{
					this.OnbCreditByHeadChanging(value);
					this.SendPropertyChanging();
					this._bCreditByHead = value;
					this.SendPropertyChanged("bCreditByHead");
					this.OnbCreditByHeadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bLicenceDate", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bLicenceDate
		{
			get
			{
				return this._bLicenceDate;
			}
			set
			{
				if ((this._bLicenceDate != value))
				{
					this.OnbLicenceDateChanging(value);
					this.SendPropertyChanging();
					this._bLicenceDate = value;
					this.SendPropertyChanged("bLicenceDate");
					this.OnbLicenceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dLicenceSDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dLicenceSDate
		{
			get
			{
				return this._dLicenceSDate;
			}
			set
			{
				if ((this._dLicenceSDate != value))
				{
					this.OndLicenceSDateChanging(value);
					this.SendPropertyChanging();
					this._dLicenceSDate = value;
					this.SendPropertyChanged("dLicenceSDate");
					this.OndLicenceSDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dLicenceEDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dLicenceEDate
		{
			get
			{
				return this._dLicenceEDate;
			}
			set
			{
				if ((this._dLicenceEDate != value))
				{
					this.OndLicenceEDateChanging(value);
					this.SendPropertyChanging();
					this._dLicenceEDate = value;
					this.SendPropertyChanged("dLicenceEDate");
					this.OndLicenceEDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLicenceADays", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> iLicenceADays
		{
			get
			{
				return this._iLicenceADays;
			}
			set
			{
				if ((this._iLicenceADays != value))
				{
					this.OniLicenceADaysChanging(value);
					this.SendPropertyChanging();
					this._iLicenceADays = value;
					this.SendPropertyChanged("iLicenceADays");
					this.OniLicenceADaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bBusinessDate", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bBusinessDate
		{
			get
			{
				return this._bBusinessDate;
			}
			set
			{
				if ((this._bBusinessDate != value))
				{
					this.OnbBusinessDateChanging(value);
					this.SendPropertyChanging();
					this._bBusinessDate = value;
					this.SendPropertyChanged("bBusinessDate");
					this.OnbBusinessDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dBusinessSDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dBusinessSDate
		{
			get
			{
				return this._dBusinessSDate;
			}
			set
			{
				if ((this._dBusinessSDate != value))
				{
					this.OndBusinessSDateChanging(value);
					this.SendPropertyChanging();
					this._dBusinessSDate = value;
					this.SendPropertyChanged("dBusinessSDate");
					this.OndBusinessSDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dBusinessEDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dBusinessEDate
		{
			get
			{
				return this._dBusinessEDate;
			}
			set
			{
				if ((this._dBusinessEDate != value))
				{
					this.OndBusinessEDateChanging(value);
					this.SendPropertyChanging();
					this._dBusinessEDate = value;
					this.SendPropertyChanged("dBusinessEDate");
					this.OndBusinessEDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iBusinessADays", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> iBusinessADays
		{
			get
			{
				return this._iBusinessADays;
			}
			set
			{
				if ((this._iBusinessADays != value))
				{
					this.OniBusinessADaysChanging(value);
					this.SendPropertyChanging();
					this._iBusinessADays = value;
					this.SendPropertyChanged("iBusinessADays");
					this.OniBusinessADaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bProxy", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bProxy
		{
			get
			{
				return this._bProxy;
			}
			set
			{
				if ((this._bProxy != value))
				{
					this.OnbProxyChanging(value);
					this.SendPropertyChanging();
					this._bProxy = value;
					this.SendPropertyChanged("bProxy");
					this.OnbProxyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dProxySDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dProxySDate
		{
			get
			{
				return this._dProxySDate;
			}
			set
			{
				if ((this._dProxySDate != value))
				{
					this.OndProxySDateChanging(value);
					this.SendPropertyChanging();
					this._dProxySDate = value;
					this.SendPropertyChanged("dProxySDate");
					this.OndProxySDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dProxyEDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dProxyEDate
		{
			get
			{
				return this._dProxyEDate;
			}
			set
			{
				if ((this._dProxyEDate != value))
				{
					this.OndProxyEDateChanging(value);
					this.SendPropertyChanging();
					this._dProxyEDate = value;
					this.SendPropertyChanged("dProxyEDate");
					this.OndProxyEDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iProxyADays", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> iProxyADays
		{
			get
			{
				return this._iProxyADays;
			}
			set
			{
				if ((this._iProxyADays != value))
				{
					this.OniProxyADaysChanging(value);
					this.SendPropertyChanging();
					this._iProxyADays = value;
					this.SendPropertyChanged("iProxyADays");
					this.OniProxyADaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cMemo", DbType="NVarChar(240)", UpdateCheck=UpdateCheck.Never)]
		public string cMemo
		{
			get
			{
				return this._cMemo;
			}
			set
			{
				if ((this._cMemo != value))
				{
					this.OncMemoChanging(value);
					this.SendPropertyChanging();
					this._cMemo = value;
					this.SendPropertyChanged("cMemo");
					this.OncMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bLimitSale", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bLimitSale
		{
			get
			{
				return this._bLimitSale;
			}
			set
			{
				if ((this._bLimitSale != value))
				{
					this.OnbLimitSaleChanging(value);
					this.SendPropertyChanging();
					this._bLimitSale = value;
					this.SendPropertyChanged("bLimitSale");
					this.OnbLimitSaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusContactCode", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> cCusContactCode
		{
			get
			{
				return this._cCusContactCode;
			}
			set
			{
				if ((this._cCusContactCode != value))
				{
					this.OncCusContactCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusContactCode = value;
					this.SendPropertyChanged("cCusContactCode");
					this.OncCusContactCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusCountryCode", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string cCusCountryCode
		{
			get
			{
				return this._cCusCountryCode;
			}
			set
			{
				if ((this._cCusCountryCode != value))
				{
					this.OncCusCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusCountryCode = value;
					this.SendPropertyChanged("cCusCountryCode");
					this.OncCusCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusEnName", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string cCusEnName
		{
			get
			{
				return this._cCusEnName;
			}
			set
			{
				if ((this._cCusEnName != value))
				{
					this.OncCusEnNameChanging(value);
					this.SendPropertyChanging();
					this._cCusEnName = value;
					this.SendPropertyChanged("cCusEnName");
					this.OncCusEnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusEnAddr1", DbType="NVarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string cCusEnAddr1
		{
			get
			{
				return this._cCusEnAddr1;
			}
			set
			{
				if ((this._cCusEnAddr1 != value))
				{
					this.OncCusEnAddr1Changing(value);
					this.SendPropertyChanging();
					this._cCusEnAddr1 = value;
					this.SendPropertyChanged("cCusEnAddr1");
					this.OncCusEnAddr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusEnAddr2", DbType="NVarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string cCusEnAddr2
		{
			get
			{
				return this._cCusEnAddr2;
			}
			set
			{
				if ((this._cCusEnAddr2 != value))
				{
					this.OncCusEnAddr2Changing(value);
					this.SendPropertyChanging();
					this._cCusEnAddr2 = value;
					this.SendPropertyChanged("cCusEnAddr2");
					this.OncCusEnAddr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusEnAddr3", DbType="NVarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string cCusEnAddr3
		{
			get
			{
				return this._cCusEnAddr3;
			}
			set
			{
				if ((this._cCusEnAddr3 != value))
				{
					this.OncCusEnAddr3Changing(value);
					this.SendPropertyChanging();
					this._cCusEnAddr3 = value;
					this.SendPropertyChanged("cCusEnAddr3");
					this.OncCusEnAddr3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusEnAddr4", DbType="NVarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string cCusEnAddr4
		{
			get
			{
				return this._cCusEnAddr4;
			}
			set
			{
				if ((this._cCusEnAddr4 != value))
				{
					this.OncCusEnAddr4Changing(value);
					this.SendPropertyChanging();
					this._cCusEnAddr4 = value;
					this.SendPropertyChanged("cCusEnAddr4");
					this.OncCusEnAddr4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusPortCode", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string cCusPortCode
		{
			get
			{
				return this._cCusPortCode;
			}
			set
			{
				if ((this._cCusPortCode != value))
				{
					this.OncCusPortCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusPortCode = value;
					this.SendPropertyChanged("cCusPortCode");
					this.OncCusPortCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cPrimaryVen", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cPrimaryVen
		{
			get
			{
				return this._cPrimaryVen;
			}
			set
			{
				if ((this._cPrimaryVen != value))
				{
					this.OncPrimaryVenChanging(value);
					this.SendPropertyChanging();
					this._cPrimaryVen = value;
					this.SendPropertyChanged("cPrimaryVen");
					this.OncPrimaryVenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCommisionRate", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> fCommisionRate
		{
			get
			{
				return this._fCommisionRate;
			}
			set
			{
				if ((this._fCommisionRate != value))
				{
					this.OnfCommisionRateChanging(value);
					this.SendPropertyChanging();
					this._fCommisionRate = value;
					this.SendPropertyChanged("fCommisionRate");
					this.OnfCommisionRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fInsueRate", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> fInsueRate
		{
			get
			{
				return this._fInsueRate;
			}
			set
			{
				if ((this._fInsueRate != value))
				{
					this.OnfInsueRateChanging(value);
					this.SendPropertyChanging();
					this._fInsueRate = value;
					this.SendPropertyChanged("fInsueRate");
					this.OnfInsueRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bHomeBranch", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bHomeBranch
		{
			get
			{
				return this._bHomeBranch;
			}
			set
			{
				if ((this._bHomeBranch != value))
				{
					this.OnbHomeBranchChanging(value);
					this.SendPropertyChanging();
					this._bHomeBranch = value;
					this.SendPropertyChanged("bHomeBranch");
					this.OnbHomeBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cBranchAddr", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string cBranchAddr
		{
			get
			{
				return this._cBranchAddr;
			}
			set
			{
				if ((this._cBranchAddr != value))
				{
					this.OncBranchAddrChanging(value);
					this.SendPropertyChanging();
					this._cBranchAddr = value;
					this.SendPropertyChanged("cBranchAddr");
					this.OncBranchAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cBranchPhone", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string cBranchPhone
		{
			get
			{
				return this._cBranchPhone;
			}
			set
			{
				if ((this._cBranchPhone != value))
				{
					this.OncBranchPhoneChanging(value);
					this.SendPropertyChanging();
					this._cBranchPhone = value;
					this.SendPropertyChanged("cBranchPhone");
					this.OncBranchPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cBranchPerson", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cBranchPerson
		{
			get
			{
				return this._cBranchPerson;
			}
			set
			{
				if ((this._cBranchPerson != value))
				{
					this.OncBranchPersonChanging(value);
					this.SendPropertyChanging();
					this._cBranchPerson = value;
					this.SendPropertyChanged("cBranchPerson");
					this.OncBranchPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusTradeCCode", DbType="NVarChar(12)", UpdateCheck=UpdateCheck.Never)]
		public string cCusTradeCCode
		{
			get
			{
				return this._cCusTradeCCode;
			}
			set
			{
				if ((this._cCusTradeCCode != value))
				{
					this.OncCusTradeCCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusTradeCCode = value;
					this.SendPropertyChanged("cCusTradeCCode");
					this.OncCusTradeCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerKCode", DbType="NVarChar(4)", UpdateCheck=UpdateCheck.Never)]
		public string CustomerKCode
		{
			get
			{
				return this._CustomerKCode;
			}
			set
			{
				if ((this._CustomerKCode != value))
				{
					this.OnCustomerKCodeChanging(value);
					this.SendPropertyChanging();
					this._CustomerKCode = value;
					this.SendPropertyChanged("CustomerKCode");
					this.OnCustomerKCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bCusState", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bCusState
		{
			get
			{
				return this._bCusState;
			}
			set
			{
				if ((this._bCusState != value))
				{
					this.OnbCusStateChanging(value);
					this.SendPropertyChanging();
					this._bCusState = value;
					this.SendPropertyChanged("bCusState");
					this.OnbCusStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bShop", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bShop
		{
			get
			{
				return this._bShop;
			}
			set
			{
				if ((this._bShop != value))
				{
					this.OnbShopChanging(value);
					this.SendPropertyChanging();
					this._bShop = value;
					this.SendPropertyChanged("bShop");
					this.OnbShopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusBankCode", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cCusBankCode
		{
			get
			{
				return this._cCusBankCode;
			}
			set
			{
				if ((this._cCusBankCode != value))
				{
					this.OncCusBankCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusBankCode = value;
					this.SendPropertyChanged("cCusBankCode");
					this.OncCusBankCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusExch_name", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cCusExch_name
		{
			get
			{
				return this._cCusExch_name;
			}
			set
			{
				if ((this._cCusExch_name != value))
				{
					this.OncCusExch_nameChanging(value);
					this.SendPropertyChanging();
					this._cCusExch_name = value;
					this.SendPropertyChanged("cCusExch_name");
					this.OncCusExch_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCusGSPType", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short iCusGSPType
		{
			get
			{
				return this._iCusGSPType;
			}
			set
			{
				if ((this._iCusGSPType != value))
				{
					this.OniCusGSPTypeChanging(value);
					this.SendPropertyChanging();
					this._iCusGSPType = value;
					this.SendPropertyChanged("iCusGSPType");
					this.OniCusGSPTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCusGSPAuth", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> iCusGSPAuth
		{
			get
			{
				return this._iCusGSPAuth;
			}
			set
			{
				if ((this._iCusGSPAuth != value))
				{
					this.OniCusGSPAuthChanging(value);
					this.SendPropertyChanging();
					this._iCusGSPAuth = value;
					this.SendPropertyChanged("iCusGSPAuth");
					this.OniCusGSPAuthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusGSPAuthNo", DbType="NVarChar(40)", UpdateCheck=UpdateCheck.Never)]
		public string cCusGSPAuthNo
		{
			get
			{
				return this._cCusGSPAuthNo;
			}
			set
			{
				if ((this._cCusGSPAuthNo != value))
				{
					this.OncCusGSPAuthNoChanging(value);
					this.SendPropertyChanging();
					this._cCusGSPAuthNo = value;
					this.SendPropertyChanged("cCusGSPAuthNo");
					this.OncCusGSPAuthNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusBusinessNo", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusBusinessNo
		{
			get
			{
				return this._cCusBusinessNo;
			}
			set
			{
				if ((this._cCusBusinessNo != value))
				{
					this.OncCusBusinessNoChanging(value);
					this.SendPropertyChanging();
					this._cCusBusinessNo = value;
					this.SendPropertyChanged("cCusBusinessNo");
					this.OncCusBusinessNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusLicenceNo", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusLicenceNo
		{
			get
			{
				return this._cCusLicenceNo;
			}
			set
			{
				if ((this._cCusLicenceNo != value))
				{
					this.OncCusLicenceNoChanging(value);
					this.SendPropertyChanging();
					this._cCusLicenceNo = value;
					this.SendPropertyChanged("cCusLicenceNo");
					this.OncCusLicenceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bCusDomestic", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bCusDomestic
		{
			get
			{
				return this._bCusDomestic;
			}
			set
			{
				if ((this._bCusDomestic != value))
				{
					this.OnbCusDomesticChanging(value);
					this.SendPropertyChanging();
					this._bCusDomestic = value;
					this.SendPropertyChanged("bCusDomestic");
					this.OnbCusDomesticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bCusOverseas", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool bCusOverseas
		{
			get
			{
				return this._bCusOverseas;
			}
			set
			{
				if ((this._bCusOverseas != value))
				{
					this.OnbCusOverseasChanging(value);
					this.SendPropertyChanging();
					this._bCusOverseas = value;
					this.SendPropertyChanged("bCusOverseas");
					this.OnbCusOverseasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusCreditCompany", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusCreditCompany
		{
			get
			{
				return this._cCusCreditCompany;
			}
			set
			{
				if ((this._cCusCreditCompany != value))
				{
					this.OncCusCreditCompanyChanging(value);
					this.SendPropertyChanging();
					this._cCusCreditCompany = value;
					this.SendPropertyChanged("cCusCreditCompany");
					this.OncCusCreditCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusSAProtocol", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusSAProtocol
		{
			get
			{
				return this._cCusSAProtocol;
			}
			set
			{
				if ((this._cCusSAProtocol != value))
				{
					this.OncCusSAProtocolChanging(value);
					this.SendPropertyChanging();
					this._cCusSAProtocol = value;
					this.SendPropertyChanged("cCusSAProtocol");
					this.OncCusSAProtocolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusExProtocol", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusExProtocol
		{
			get
			{
				return this._cCusExProtocol;
			}
			set
			{
				if ((this._cCusExProtocol != value))
				{
					this.OncCusExProtocolChanging(value);
					this.SendPropertyChanging();
					this._cCusExProtocol = value;
					this.SendPropertyChanged("cCusExProtocol");
					this.OncCusExProtocolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusOtherProtocol", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusOtherProtocol
		{
			get
			{
				return this._cCusOtherProtocol;
			}
			set
			{
				if ((this._cCusOtherProtocol != value))
				{
					this.OncCusOtherProtocolChanging(value);
					this.SendPropertyChanging();
					this._cCusOtherProtocol = value;
					this.SendPropertyChanged("cCusOtherProtocol");
					this.OncCusOtherProtocolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCusDiscountRate", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> fCusDiscountRate
		{
			get
			{
				return this._fCusDiscountRate;
			}
			set
			{
				if ((this._fCusDiscountRate != value))
				{
					this.OnfCusDiscountRateChanging(value);
					this.SendPropertyChanging();
					this._fCusDiscountRate = value;
					this.SendPropertyChanged("fCusDiscountRate");
					this.OnfCusDiscountRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusSSCode", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusSSCode
		{
			get
			{
				return this._cCusSSCode;
			}
			set
			{
				if ((this._cCusSSCode != value))
				{
					this.OncCusSSCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusSSCode = value;
					this.SendPropertyChanged("cCusSSCode");
					this.OncCusSSCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusCMProtocol", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string cCusCMProtocol
		{
			get
			{
				return this._cCusCMProtocol;
			}
			set
			{
				if ((this._cCusCMProtocol != value))
				{
					this.OncCusCMProtocolChanging(value);
					this.SendPropertyChanging();
					this._cCusCMProtocol = value;
					this.SendPropertyChanged("cCusCMProtocol");
					this.OncCusCMProtocolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dCusCreateDatetime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime dCusCreateDatetime
		{
			get
			{
				return this._dCusCreateDatetime;
			}
			set
			{
				if ((this._dCusCreateDatetime != value))
				{
					this.OndCusCreateDatetimeChanging(value);
					this.SendPropertyChanging();
					this._dCusCreateDatetime = value;
					this.SendPropertyChanged("dCusCreateDatetime");
					this.OndCusCreateDatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusAppDocNo", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cCusAppDocNo
		{
			get
			{
				return this._cCusAppDocNo;
			}
			set
			{
				if ((this._cCusAppDocNo != value))
				{
					this.OncCusAppDocNoChanging(value);
					this.SendPropertyChanging();
					this._cCusAppDocNo = value;
					this.SendPropertyChanged("cCusAppDocNo");
					this.OncCusAppDocNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
