#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouHoo.DataBll.VISIT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KeChuange")]
	public partial class VisitDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertyouhoo_Visit_Record(youhoo_Visit_Record instance);
    partial void Updateyouhoo_Visit_Record(youhoo_Visit_Record instance);
    partial void Deleteyouhoo_Visit_Record(youhoo_Visit_Record instance);
    #endregion
		
		public VisitDataContext() : 
				base(global::YouHoo.DataBll.Properties.Settings.Default.KeChuangeConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public VisitDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VisitDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VisitDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VisitDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<youhoo_Visit_Record> youhoo_Visit_Record
		{
			get
			{
				return this.GetTable<youhoo_Visit_Record>();
			}
		}
		
		public System.Data.Linq.Table<v_VisitRecordWay> v_VisitRecordWay
		{
			get
			{
				return this.GetTable<v_VisitRecordWay>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.youhoo_Visit_Record")]
	public partial class youhoo_Visit_Record : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _visit_id;
		
		private string _cCusName;
		
		private string _cCusAbbName;
		
		private string _cCusCode;
		
		private string _phoneNumber;
		
		private string _cCusPerson;
		
		private System.DateTime _visit_date;
		
		private string _visit_location;
		
		private string _visit_person;
		
		private System.DateTime _visit_startTime;
		
		private System.DateTime _visit_endTime;
		
		private System.Nullable<int> _visit_way_id;
		
		private string _visit_content;
		
		private string _visit_NextPlan;
		
		private string _visit_ManagerOpinion;
		
		private int _verifi_state;
		
		private string _remark;
		
		private System.Nullable<int> _flag;
		
		private int _user_id;
		
		private string _createoperator;
		
		private System.Nullable<System.DateTime> _createdate;
		
		private string _updateoperator;
		
		private System.Nullable<System.DateTime> _updatedate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvisit_idChanging(int value);
    partial void Onvisit_idChanged();
    partial void OncCusNameChanging(string value);
    partial void OncCusNameChanged();
    partial void OncCusAbbNameChanging(string value);
    partial void OncCusAbbNameChanged();
    partial void OncCusCodeChanging(string value);
    partial void OncCusCodeChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    partial void OncCusPersonChanging(string value);
    partial void OncCusPersonChanged();
    partial void Onvisit_dateChanging(System.DateTime value);
    partial void Onvisit_dateChanged();
    partial void Onvisit_locationChanging(string value);
    partial void Onvisit_locationChanged();
    partial void Onvisit_personChanging(string value);
    partial void Onvisit_personChanged();
    partial void Onvisit_startTimeChanging(System.DateTime value);
    partial void Onvisit_startTimeChanged();
    partial void Onvisit_endTimeChanging(System.DateTime value);
    partial void Onvisit_endTimeChanged();
    partial void Onvisit_way_idChanging(System.Nullable<int> value);
    partial void Onvisit_way_idChanged();
    partial void Onvisit_contentChanging(string value);
    partial void Onvisit_contentChanged();
    partial void Onvisit_NextPlanChanging(string value);
    partial void Onvisit_NextPlanChanged();
    partial void Onvisit_ManagerOpinionChanging(string value);
    partial void Onvisit_ManagerOpinionChanged();
    partial void Onverifi_stateChanging(int value);
    partial void Onverifi_stateChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnflagChanging(System.Nullable<int> value);
    partial void OnflagChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OncreateoperatorChanging(string value);
    partial void OncreateoperatorChanged();
    partial void OncreatedateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedateChanged();
    partial void OnupdateoperatorChanging(string value);
    partial void OnupdateoperatorChanged();
    partial void OnupdatedateChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedateChanged();
    #endregion
		
		public youhoo_Visit_Record()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int visit_id
		{
			get
			{
				return this._visit_id;
			}
			set
			{
				if ((this._visit_id != value))
				{
					this.Onvisit_idChanging(value);
					this.SendPropertyChanging();
					this._visit_id = value;
					this.SendPropertyChanged("visit_id");
					this.Onvisit_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusName", DbType="NVarChar(98) NOT NULL", CanBeNull=false)]
		public string cCusName
		{
			get
			{
				return this._cCusName;
			}
			set
			{
				if ((this._cCusName != value))
				{
					this.OncCusNameChanging(value);
					this.SendPropertyChanging();
					this._cCusName = value;
					this.SendPropertyChanged("cCusName");
					this.OncCusNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusAbbName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string cCusAbbName
		{
			get
			{
				return this._cCusAbbName;
			}
			set
			{
				if ((this._cCusAbbName != value))
				{
					this.OncCusAbbNameChanging(value);
					this.SendPropertyChanging();
					this._cCusAbbName = value;
					this.SendPropertyChanged("cCusAbbName");
					this.OncCusAbbNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string cCusCode
		{
			get
			{
				return this._cCusCode;
			}
			set
			{
				if ((this._cCusCode != value))
				{
					this.OncCusCodeChanging(value);
					this.SendPropertyChanging();
					this._cCusCode = value;
					this.SendPropertyChanged("cCusCode");
					this.OncCusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusPerson", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cCusPerson
		{
			get
			{
				return this._cCusPerson;
			}
			set
			{
				if ((this._cCusPerson != value))
				{
					this.OncCusPersonChanging(value);
					this.SendPropertyChanging();
					this._cCusPerson = value;
					this.SendPropertyChanged("cCusPerson");
					this.OncCusPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_date", DbType="DateTime NOT NULL")]
		public System.DateTime visit_date
		{
			get
			{
				return this._visit_date;
			}
			set
			{
				if ((this._visit_date != value))
				{
					this.Onvisit_dateChanging(value);
					this.SendPropertyChanging();
					this._visit_date = value;
					this.SendPropertyChanged("visit_date");
					this.Onvisit_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_location", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string visit_location
		{
			get
			{
				return this._visit_location;
			}
			set
			{
				if ((this._visit_location != value))
				{
					this.Onvisit_locationChanging(value);
					this.SendPropertyChanging();
					this._visit_location = value;
					this.SendPropertyChanged("visit_location");
					this.Onvisit_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_person", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string visit_person
		{
			get
			{
				return this._visit_person;
			}
			set
			{
				if ((this._visit_person != value))
				{
					this.Onvisit_personChanging(value);
					this.SendPropertyChanging();
					this._visit_person = value;
					this.SendPropertyChanged("visit_person");
					this.Onvisit_personChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_startTime", DbType="DateTime NOT NULL")]
		public System.DateTime visit_startTime
		{
			get
			{
				return this._visit_startTime;
			}
			set
			{
				if ((this._visit_startTime != value))
				{
					this.Onvisit_startTimeChanging(value);
					this.SendPropertyChanging();
					this._visit_startTime = value;
					this.SendPropertyChanged("visit_startTime");
					this.Onvisit_startTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_endTime", DbType="DateTime NOT NULL")]
		public System.DateTime visit_endTime
		{
			get
			{
				return this._visit_endTime;
			}
			set
			{
				if ((this._visit_endTime != value))
				{
					this.Onvisit_endTimeChanging(value);
					this.SendPropertyChanging();
					this._visit_endTime = value;
					this.SendPropertyChanged("visit_endTime");
					this.Onvisit_endTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_way_id", DbType="Int")]
		public System.Nullable<int> visit_way_id
		{
			get
			{
				return this._visit_way_id;
			}
			set
			{
				if ((this._visit_way_id != value))
				{
					this.Onvisit_way_idChanging(value);
					this.SendPropertyChanging();
					this._visit_way_id = value;
					this.SendPropertyChanged("visit_way_id");
					this.Onvisit_way_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_content", DbType="NVarChar(400)")]
		public string visit_content
		{
			get
			{
				return this._visit_content;
			}
			set
			{
				if ((this._visit_content != value))
				{
					this.Onvisit_contentChanging(value);
					this.SendPropertyChanging();
					this._visit_content = value;
					this.SendPropertyChanged("visit_content");
					this.Onvisit_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_NextPlan", DbType="NVarChar(300)")]
		public string visit_NextPlan
		{
			get
			{
				return this._visit_NextPlan;
			}
			set
			{
				if ((this._visit_NextPlan != value))
				{
					this.Onvisit_NextPlanChanging(value);
					this.SendPropertyChanging();
					this._visit_NextPlan = value;
					this.SendPropertyChanged("visit_NextPlan");
					this.Onvisit_NextPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_ManagerOpinion", DbType="NChar(10)")]
		public string visit_ManagerOpinion
		{
			get
			{
				return this._visit_ManagerOpinion;
			}
			set
			{
				if ((this._visit_ManagerOpinion != value))
				{
					this.Onvisit_ManagerOpinionChanging(value);
					this.SendPropertyChanging();
					this._visit_ManagerOpinion = value;
					this.SendPropertyChanged("visit_ManagerOpinion");
					this.Onvisit_ManagerOpinionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verifi_state", DbType="Int NOT NULL")]
		public int verifi_state
		{
			get
			{
				return this._verifi_state;
			}
			set
			{
				if ((this._verifi_state != value))
				{
					this.Onverifi_stateChanging(value);
					this.SendPropertyChanging();
					this._verifi_state = value;
					this.SendPropertyChanged("verifi_state");
					this.Onverifi_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag", DbType="Int")]
		public System.Nullable<int> flag
		{
			get
			{
				return this._flag;
			}
			set
			{
				if ((this._flag != value))
				{
					this.OnflagChanging(value);
					this.SendPropertyChanging();
					this._flag = value;
					this.SendPropertyChanged("flag");
					this.OnflagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createoperator", DbType="NVarChar(50)")]
		public string createoperator
		{
			get
			{
				return this._createoperator;
			}
			set
			{
				if ((this._createoperator != value))
				{
					this.OncreateoperatorChanging(value);
					this.SendPropertyChanging();
					this._createoperator = value;
					this.SendPropertyChanged("createoperator");
					this.OncreateoperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				if ((this._createdate != value))
				{
					this.OncreatedateChanging(value);
					this.SendPropertyChanging();
					this._createdate = value;
					this.SendPropertyChanged("createdate");
					this.OncreatedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateoperator", DbType="NVarChar(50)")]
		public string updateoperator
		{
			get
			{
				return this._updateoperator;
			}
			set
			{
				if ((this._updateoperator != value))
				{
					this.OnupdateoperatorChanging(value);
					this.SendPropertyChanging();
					this._updateoperator = value;
					this.SendPropertyChanged("updateoperator");
					this.OnupdateoperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedate", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				if ((this._updatedate != value))
				{
					this.OnupdatedateChanging(value);
					this.SendPropertyChanging();
					this._updatedate = value;
					this.SendPropertyChanged("updatedate");
					this.OnupdatedateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_VisitRecordWay")]
	public partial class v_VisitRecordWay
	{
		
		private int _visit_id;
		
		private string _cCusName;
		
		private string _cCusAbbName;
		
		private string _cCusCode;
		
		private string _phoneNumber;
		
		private string _cCusPerson;
		
		private System.DateTime _visit_date;
		
		private string _visit_location;
		
		private string _visit_person;
		
		private System.DateTime _visit_startTime;
		
		private System.DateTime _visit_endTime;
		
		private System.Nullable<int> _visit_way_id;
		
		private string _visit_content;
		
		private string _visit_NextPlan;
		
		private string _visit_ManagerOpinion;
		
		private int _verifi_state;
		
		private string _remark;
		
		private System.Nullable<int> _flag;
		
		private int _user_id;
		
		private string _createoperator;
		
		private System.Nullable<System.DateTime> _createdate;
		
		private string _updateoperator;
		
		private System.Nullable<System.DateTime> _updatedate;
		
		private string _visit_name;
		
		public v_VisitRecordWay()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_id", DbType="Int NOT NULL")]
		public int visit_id
		{
			get
			{
				return this._visit_id;
			}
			set
			{
				if ((this._visit_id != value))
				{
					this._visit_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusName", DbType="NVarChar(98) NOT NULL", CanBeNull=false)]
		public string cCusName
		{
			get
			{
				return this._cCusName;
			}
			set
			{
				if ((this._cCusName != value))
				{
					this._cCusName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusAbbName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string cCusAbbName
		{
			get
			{
				return this._cCusAbbName;
			}
			set
			{
				if ((this._cCusAbbName != value))
				{
					this._cCusAbbName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string cCusCode
		{
			get
			{
				return this._cCusCode;
			}
			set
			{
				if ((this._cCusCode != value))
				{
					this._cCusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneNumber", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this._phoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCusPerson", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cCusPerson
		{
			get
			{
				return this._cCusPerson;
			}
			set
			{
				if ((this._cCusPerson != value))
				{
					this._cCusPerson = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_date", DbType="DateTime NOT NULL")]
		public System.DateTime visit_date
		{
			get
			{
				return this._visit_date;
			}
			set
			{
				if ((this._visit_date != value))
				{
					this._visit_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_location", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string visit_location
		{
			get
			{
				return this._visit_location;
			}
			set
			{
				if ((this._visit_location != value))
				{
					this._visit_location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_person", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string visit_person
		{
			get
			{
				return this._visit_person;
			}
			set
			{
				if ((this._visit_person != value))
				{
					this._visit_person = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_startTime", DbType="DateTime NOT NULL")]
		public System.DateTime visit_startTime
		{
			get
			{
				return this._visit_startTime;
			}
			set
			{
				if ((this._visit_startTime != value))
				{
					this._visit_startTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_endTime", DbType="DateTime NOT NULL")]
		public System.DateTime visit_endTime
		{
			get
			{
				return this._visit_endTime;
			}
			set
			{
				if ((this._visit_endTime != value))
				{
					this._visit_endTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_way_id", DbType="Int")]
		public System.Nullable<int> visit_way_id
		{
			get
			{
				return this._visit_way_id;
			}
			set
			{
				if ((this._visit_way_id != value))
				{
					this._visit_way_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_content", DbType="NVarChar(400)")]
		public string visit_content
		{
			get
			{
				return this._visit_content;
			}
			set
			{
				if ((this._visit_content != value))
				{
					this._visit_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_NextPlan", DbType="NVarChar(300)")]
		public string visit_NextPlan
		{
			get
			{
				return this._visit_NextPlan;
			}
			set
			{
				if ((this._visit_NextPlan != value))
				{
					this._visit_NextPlan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_ManagerOpinion", DbType="NChar(10)")]
		public string visit_ManagerOpinion
		{
			get
			{
				return this._visit_ManagerOpinion;
			}
			set
			{
				if ((this._visit_ManagerOpinion != value))
				{
					this._visit_ManagerOpinion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verifi_state", DbType="Int NOT NULL")]
		public int verifi_state
		{
			get
			{
				return this._verifi_state;
			}
			set
			{
				if ((this._verifi_state != value))
				{
					this._verifi_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag", DbType="Int")]
		public System.Nullable<int> flag
		{
			get
			{
				return this._flag;
			}
			set
			{
				if ((this._flag != value))
				{
					this._flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createoperator", DbType="NVarChar(50)")]
		public string createoperator
		{
			get
			{
				return this._createoperator;
			}
			set
			{
				if ((this._createoperator != value))
				{
					this._createoperator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				if ((this._createdate != value))
				{
					this._createdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateoperator", DbType="NVarChar(50)")]
		public string updateoperator
		{
			get
			{
				return this._updateoperator;
			}
			set
			{
				if ((this._updateoperator != value))
				{
					this._updateoperator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedate", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				if ((this._updatedate != value))
				{
					this._updatedate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_name", DbType="NVarChar(50)")]
		public string visit_name
		{
			get
			{
				return this._visit_name;
			}
			set
			{
				if ((this._visit_name != value))
				{
					this._visit_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
