//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeChuangeEntities : DbContext
    {
        public KeChuangeEntities()
            : base("name=KeChuangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<youhoo_BasicArchive_brand> youhoo_BasicArchive_brand { get; set; }
        public virtual DbSet<youhoo_BasicArchive_channel> youhoo_BasicArchive_channel { get; set; }
        public virtual DbSet<youhoo_BasicArchive_item> youhoo_BasicArchive_item { get; set; }
        public virtual DbSet<youhoo_BasicArchive_price> youhoo_BasicArchive_price { get; set; }
        public virtual DbSet<youhoo_BasicArchive_region> youhoo_BasicArchive_region { get; set; }
        public virtual DbSet<youhoo_BasicArchive_sort> youhoo_BasicArchive_sort { get; set; }
        public virtual DbSet<youhoo_BasicArchive_SupportPrice> youhoo_BasicArchive_SupportPrice { get; set; }
        public virtual DbSet<youhoo_BasicArchive_SupportWay> youhoo_BasicArchive_SupportWay { get; set; }
        public virtual DbSet<youhoo_BasicArchive_time> youhoo_BasicArchive_time { get; set; }
        public virtual DbSet<youhoo_rebate_RebatePolicy> youhoo_rebate_RebatePolicy { get; set; }
        public virtual DbSet<youhoo_rebate_RebatePolicys> youhoo_rebate_RebatePolicys { get; set; }
        public virtual DbSet<youhoo_rebate_RebateWay> youhoo_rebate_RebateWay { get; set; }
        public virtual DbSet<youhoo_rebate_sale> youhoo_rebate_sale { get; set; }
        public virtual DbSet<youhoo_sys_action> youhoo_sys_action { get; set; }
        public virtual DbSet<youhoo_sys_Department> youhoo_sys_Department { get; set; }
        public virtual DbSet<youhoo_sys_dictionary> youhoo_sys_dictionary { get; set; }
        public virtual DbSet<youhoo_sys_dictionary_child> youhoo_sys_dictionary_child { get; set; }
        public virtual DbSet<youhoo_sys_files> youhoo_sys_files { get; set; }
        public virtual DbSet<youhoo_sys_module> youhoo_sys_module { get; set; }
        public virtual DbSet<youhoo_sys_node> youhoo_sys_node { get; set; }
        public virtual DbSet<youhoo_sys_power> youhoo_sys_power { get; set; }
        public virtual DbSet<youhoo_sys_powergroup> youhoo_sys_powergroup { get; set; }
        public virtual DbSet<Youhoo_sys_Process> Youhoo_sys_Process { get; set; }
        public virtual DbSet<youhoo_sys_Result> youhoo_sys_Result { get; set; }
        public virtual DbSet<youhoo_sys_store> youhoo_sys_store { get; set; }
        public virtual DbSet<youhoo_sys_system_set> youhoo_sys_system_set { get; set; }
        public virtual DbSet<youhoo_sys_users> youhoo_sys_users { get; set; }
    }
}
